server:
  port: 9001
spring:
  application:
    name: CustomerManagement
  datasource:
    url: jdbc:mysql://localhost:3306/customer-management
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true


